# Generated by Django 4.2.20 on 2025-05-30 13:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='דירוג מ-1 עד 5 כוכבים', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='דירוג')),
                ('message', models.TextField(blank=True, help_text='הודעה אופציונלית מהמשתמש', max_length=1000, null=True, verbose_name='הודעה')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('is_hidden', models.BooleanField(default=False, help_text='האם הביקורת מוסתרת מהציבור', verbose_name='מוסתר')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'ביקורת',
                'verbose_name_plural': 'ביקורות',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating'], name='Website_rev_rating_89168e_idx'), models.Index(fields=['created_at'], name='Website_rev_created_33a9b3_idx'), models.Index(fields=['is_hidden'], name='Website_rev_is_hidd_0d3bad_idx')],
                'unique_together': {('user',)},
            },
        ),
    ]
