# Generated by Django 4.2.20 on 2025-04-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_remove_user_is_approved_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.SmallIntegerField(default=1),
        ),
    ]
