# Generated by Django 4.2.20 on 2025-03-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Website_user',
        ),
    ]
